language: node_js
node_js:
  - stable

before_script:
  - npm run lint

deploy:
  provider: npm
  api_key:
    secure: JWMZhMwn9WzVvVHMm1ReKAUlXops0kYRqfrTUGzqr/H68lbEAHHIdJvBeijc9F5j8rJOctcuK9TSmgGacgTktPkHBI2zwTChdXKz9Uxw5iPc5pdHG9HZk99BD57JhyxPVnYdM0IcVoYN27Ahn5NLnWIaMMFUcROK868Hi/kQBCkrNBnFtGdVvl8igBlnIziK50Rdi0Q5S8bnxjslECdv/StDkBinaIGhORWm+IX8qgGcjaJtNdjC+wmDciS32kCf6aUbELY68HoH7RIDa802tsxufZxYcF8ejVY0crD7kLbuvS0eFQnga0zvS+FfYXhR4VyQi/jCKg5iF+2RFf67uLUvv1PdqUJjjMq+DwOvP/bmHfxrVplDHdWiNT5nUGQsSGBOHLJDMVIXcyYSVdtiAk1xaKLAoObUKJbdgcu8Snp2yK4ui+TK3jU4a2Eg49bEA4igGuyY9Xg9AtkF8Fbl7FGff3bEtZaxE7lXKWBSrONe1H+T6geWDlr0QDyXIjmETim553kat8NgAKd4rgYo2Oh33lJIQlr27FjZc0GnFBBrJ7yk8qzY+Z4gUZfc8ENINLy2kLV64zOHKX/T8CrlzMDPp6PpKFqs+UKixm1B4JNziXXpsSIvWnOcibsgkvesSmoVHWnwBLKrWukRW4peUiNdvmyQ6DjD5WzZvj2vCXI=
  on:
    tags: true
